title: Splunk Operator for Kubernetes
#email: your-email@example.com
description: >- 
  The Splunk Operator for Kubernetes (SOK) makes it easy for Splunk Administrators to deploy and operate Enterprise deployments in a Kubernetes infrastructure. 
  
  Packaged as a container, it uses the operator pattern to manage Splunk-specific custom resources, following best practices to manage all the underlying Kubernetes objects for you.
github_username:  mcinnesd
domain: mcinnesd.github.io 
url: "https://mcinnesd.github.io" 
favicon_ico: /assets/images/favicon.ico
aux_links:
  "Splunk Operator for Kubernetes on GitHub":
    - "//github.com/mcinnesd/splunk-operator"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-external-links
  # - jekyll-feed

krmadown:
  toc_levels: [1, 2, 3]

collections:
  helm:
    permalink: "/:path/"
    output: true
  installation:
    permalink: "/:collection/:path"
    output: true
  configuration:
    permalink: "/:collection/:path"
    output: true
  troubleshooting:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    installation:
      name: Installation
      nav_fold: true
    configuration:
      name: Configuration
      nav_fold: true
    troubleshooting:
      name: Troubleshooting
      nav_fold: true

# The colors grey-lt, grey-dk, purple,
# blue, green, yellow, and red are predefined
callouts:
  note:
    title: Note
    color: blue
  highlight:
    color: yellow

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      nav_after_collections: false
  -
    scope:
      path: ""
      type: "installation"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "configuration"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "troubleshooting"
    values:
      layout: "default"